line-length = 88
indent-width = 4
target-version = "py39"

[format]
indent-style = "space"
quote-style = "double"
line-ending = "lf"

[lint]
select = [
    "F",  # pyflakes
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "UP",  # pyupgrade
    "I",  # isort
    "A",  # flake8-builtins
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "C90",  # mccabe
    "D",  # pydocstyle
]
ignore = ["D100", "D103", "D203", "D213"]

[lint.mccabe]
max-complexity = 10
