name = "thrice"
pages_build_output_dir = "public"
compatibility_date = "2024-12-18"

[[env.staging.d1_databases]]
binding = "STAGING_DB"
database_name = "staging_thrice_db"
database_id = "09d8e34a-3b98-41e8-b046-1ef22471cc16"

[[env.production.d1_databases]]
binding = "DB"
database_name = "thrice_db"
database_id = "9b780f11-6c4b-409a-9693-98e74021ef1e"
