name = "thrice"
pages_build_output_dir = "./dist"

[[kv_namespaces]]
binding = "SESSION_CACHE"
id = "f25d58f578664c1db8f55f99077bde0b"

[[d1_databases]]
binding = "DB"
database_name = "thrice_db"
database_id = "9b780f11-6c4b-409a-9693-98e74021ef1e"

[vars]
API_KEY = "1234567asdf"
